// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    [Migration("20260317051417_TIN_Updated_Constraints")]
    partial class TIN_Updated_Constraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("7263e481-b106-4ad5-b74b-3dd232d0d761"),
                            CountryName = "Ireland"
                        },
                        new
                        {
                            CountryId = new Guid("212c665b-be6f-4b44-ab0a-ef99dbafc612"),
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryId = new Guid("0d14ef6e-8e55-476d-99f5-49be2e0c2fe8"),
                            CountryName = "Brazil"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RecieveNewsLetters")
                        .HasColumnType("bit");

                    b.Property<string>("TIN")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("TaxIdentificationNumber");

                    b.HasKey("Id");

                    b.ToTable("Persons", null, t =>
                        {
                            t.HasCheckConstraint("CHK_TIN", "len([TIN]) = 8");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("3201a91d-f003-4bae-8a79-d17985ef1e5c"),
                            Address = "HerderStr. 22, 40237 Düsseldorf",
                            CountryId = new Guid("7263e481-b106-4ad5-b74b-3dd232d0d761"),
                            Dob = new DateTime(1985, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mullallydavid7@gmail.com",
                            Gender = "Male",
                            Name = "Dengo",
                            RecieveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("62ff3027-3009-44d2-9f6c-8df737472108"),
                            Address = "HerderStr. 22, 40237 Düsseldorf",
                            CountryId = new Guid("0d14ef6e-8e55-476d-99f5-49be2e0c2fe8"),
                            Dob = new DateTime(1991, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dudalice@gmail.com",
                            Gender = "Female",
                            Name = "Doodles",
                            RecieveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("e8c5be49-f288-48d4-928a-368afbab7f7a"),
                            Address = "HerderStr. 22, 40237 Düsseldorf",
                            CountryId = new Guid("212c665b-be6f-4b44-ab0a-ef99dbafc612"),
                            Dob = new DateTime(2023, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aoife@gmail.com",
                            Gender = "Female",
                            Name = "Aoifizihna",
                            RecieveNewsLetters = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
